// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Design struct {
	ID        uuid.UUID `json:"id"`
	Prompt    string    `json:"prompt"`
	Provider  string    `json:"provider"`
	Model     string    `json:"model"`
	Status    string    `json:"status"`
	Summary   *string   `json:"summary"`
	Error     *string   `json:"error"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Event struct {
	ID        int64           `json:"id"`
	DesignID  uuid.UUID       `json:"design_id"`
	Type      string          `json:"type"`
	Data      json.RawMessage `json:"data"`
	CreatedAt time.Time       `json:"created_at"`
}

type Iteration struct {
	DesignID  uuid.UUID       `json:"design_id"`
	N         int32           `json:"n"`
	Spec      json.RawMessage `json:"spec"`
	Report    json.RawMessage `json:"report"`
	Passed    bool            `json:"passed"`
	CreatedAt time.Time       `json:"created_at"`
}
