// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createDesign = `-- name: CreateDesign :one
INSERT INTO designs (prompt, provider, model)
VALUES ($1, $2, $3)
RETURNING id, prompt, provider, model, status, summary, error, created_at, updated_at
`

type CreateDesignParams struct {
	Prompt   string `json:"prompt"`
	Provider string `json:"provider"`
	Model    string `json:"model"`
}

func (q *Queries) CreateDesign(ctx context.Context, arg CreateDesignParams) (Design, error) {
	row := q.db.QueryRow(ctx, createDesign, arg.Prompt, arg.Provider, arg.Model)
	var i Design
	err := row.Scan(
		&i.ID,
		&i.Prompt,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIteration = `-- name: CreateIteration :exec
INSERT INTO iterations (design_id, n, spec, report, passed)
VALUES ($1, $2, $3, $4, $5)
`

type CreateIterationParams struct {
	DesignID uuid.UUID       `json:"design_id"`
	N        int32           `json:"n"`
	Spec     json.RawMessage `json:"spec"`
	Report   json.RawMessage `json:"report"`
	Passed   bool            `json:"passed"`
}

func (q *Queries) CreateIteration(ctx context.Context, arg CreateIterationParams) error {
	_, err := q.db.Exec(ctx, createIteration,
		arg.DesignID,
		arg.N,
		arg.Spec,
		arg.Report,
		arg.Passed,
	)
	return err
}

const failInterruptedDesigns = `-- name: FailInterruptedDesigns :execrows
UPDATE designs
SET status = 'failed', error = 'interrupted: server restarted', updated_at = now()
WHERE status = 'running'
`

func (q *Queries) FailInterruptedDesigns(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, failInterruptedDesigns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishDesign = `-- name: FinishDesign :exec
UPDATE designs
SET status = $2, summary = $3, error = $4, updated_at = now()
WHERE id = $1
`

type FinishDesignParams struct {
	ID      uuid.UUID `json:"id"`
	Status  string    `json:"status"`
	Summary *string   `json:"summary"`
	Error   *string   `json:"error"`
}

func (q *Queries) FinishDesign(ctx context.Context, arg FinishDesignParams) error {
	_, err := q.db.Exec(ctx, finishDesign,
		arg.ID,
		arg.Status,
		arg.Summary,
		arg.Error,
	)
	return err
}

const getDesign = `-- name: GetDesign :one
SELECT id, prompt, provider, model, status, summary, error, created_at, updated_at FROM designs WHERE id = $1
`

func (q *Queries) GetDesign(ctx context.Context, id uuid.UUID) (Design, error) {
	row := q.db.QueryRow(ctx, getDesign, id)
	var i Design
	err := row.Scan(
		&i.ID,
		&i.Prompt,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (design_id, type, data)
VALUES ($1, $2, $3)
RETURNING id, design_id, type, data, created_at
`

type InsertEventParams struct {
	DesignID uuid.UUID       `json:"design_id"`
	Type     string          `json:"type"`
	Data     json.RawMessage `json:"data"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent, arg.DesignID, arg.Type, arg.Data)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.DesignID,
		&i.Type,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const listDesigns = `-- name: ListDesigns :many
SELECT d.id, d.prompt, d.provider, d.model, d.status, d.summary, d.error, d.created_at, d.updated_at, count(i.n)::int AS iteration_count
FROM designs d
LEFT JOIN iterations i ON i.design_id = d.id
GROUP BY d.id
ORDER BY d.created_at DESC
LIMIT $1
`

type ListDesignsRow struct {
	ID             uuid.UUID `json:"id"`
	Prompt         string    `json:"prompt"`
	Provider       string    `json:"provider"`
	Model          string    `json:"model"`
	Status         string    `json:"status"`
	Summary        *string   `json:"summary"`
	Error          *string   `json:"error"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	IterationCount int32     `json:"iteration_count"`
}

func (q *Queries) ListDesigns(ctx context.Context, limit int32) ([]ListDesignsRow, error) {
	rows, err := q.db.Query(ctx, listDesigns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDesignsRow
	for rows.Next() {
		var i ListDesignsRow
		if err := rows.Scan(
			&i.ID,
			&i.Prompt,
			&i.Provider,
			&i.Model,
			&i.Status,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IterationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT id, design_id, type, data, created_at FROM events
WHERE design_id = $1 AND id > $2
ORDER BY id
`

type ListEventsAfterParams struct {
	DesignID uuid.UUID `json:"design_id"`
	ID       int64     `json:"id"`
}

func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsAfter, arg.DesignID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.DesignID,
			&i.Type,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIterations = `-- name: ListIterations :many
SELECT design_id, n, spec, report, passed, created_at FROM iterations WHERE design_id = $1 ORDER BY n
`

func (q *Queries) ListIterations(ctx context.Context, designID uuid.UUID) ([]Iteration, error) {
	rows, err := q.db.Query(ctx, listIterations, designID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Iteration
	for rows.Next() {
		var i Iteration
		if err := rows.Scan(
			&i.DesignID,
			&i.N,
			&i.Spec,
			&i.Report,
			&i.Passed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
